---
title: Belle Ecole
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
promo1: |-
  オンラインレッスンを始めました！！ただいまキャンペーン中！！
  ラインやスカイプでレッスンが可能です！！
  お気軽にお問い合わせください！！
promo2: ただいま入会金 1̶0̶,̶0̶0̶0̶円　無料!
promo3: "(2024年10月10日まで!)"
privateLesson1: 40分レッスンは1回あたり 3,400円　（税込）
privateLesson2: 50分レッスンは1回あたり 3,925円　（税込）
privateLesson3: 60分レッスンは1回あたり 4,450円　（税込）
regularLesson: 月に60分4回の場合 15,700円 （税込）
groupLesson: 60分レッスン 月に4回で 一人  8,900円（税込）
openHours: 日曜と祝日はお休みです。
homeYoutubeLinkVideo: https://www.youtube.com/embed/kmZf1XNhFak
homeYoutubeLinkChanel: https://www.youtube.com/channel/UCfZkJMYMsi0D-xiTHET_CXw?sub_confirmation=1&fbclid=IwAR3vOpaq37F_HDRwA3l5dY7aaQ02qnnaEwb4nTZMDpiYkGWFTgjBV1OYBZ8
mardown: redcarpet
baseurl: "/"
exclude:
- README.md
permalink: pretty
